service: backend2
frameworkVersion: '3'

# plugins:
#   - serverless-python-requirements

custom:
  tableName: 'users-table'
  bucketName: 'image-data'

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  uploadImage:
    handler: handlers/upload.uploadImage
    events:
      - httpApi:
          path: /image
          method: post

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
	
 
 

